### ISSUE TITLE
Use render function instead

### ISSUE THREAD

**Issue by andreasvirkus** [visualfanatic/vue-svg-loader#6] opened 2017-08-04 10:40 UTC
Hello. Love the loader! But Vue complains when using it in an SSR setup:
```
[Vue warn]: You are using the runtime-only build of Vue where the template
compiler is not available. Either pre-compile the templates into render functions,
or use the compiler-included build.

found in

---> <ArrowTopIcon>
       <Sitemap>
         <Anonymous>
           <Root>
```

Any suggestions?

**Comment by visualfanatic** [comment] 2017-08-04 14:16
Could you share your SSR setup? I've created a super simple SSR app and couldn't reproduce that warning.

**Comment by andreasvirkus** [comment] 2017-08-04 14:20
Hi, unfortunately it'd be quite a hassle... But it's almost an exact copy of Vue's own hackernews 2.0 example (at least the important parts like `entry-server.js`, `entry-client.js`, `main.js`, both webpack configs, etc). Could you share the usage in your simple SSR app?

**Comment by 4ver** [comment] 2017-08-09 09:52
https://github.com/visualfanatic/vue-svg-loader/pull/8

**Comment by visualfanatic** [comment] 2017-08-19 15:17
@andreasvirkus could you update to v0.2 and tell me if the SSR works now?

**Comment by visualfanatic** [comment] 2017-10-22 21:48
I am closing this for now, please create a new issue if you still have this or similar problem, will do my best to help :+1:

**Closed by visualfanatic** 2017-10-22 21:48 UTC
